url: http://coding4art.com
name: 'Maurizio&#039;s blog 3.0'
description: 'Software architect, developer, geek boy, technology addicted and much more, with a huge passion for 70&#039;s rock-blues music'
